project:
  type: book
  output-dir: docs

book:
  title: Comparando listas e rankings
  author: "Fernando Náufel"
  date: now
  output-file: comparando
  search: true
  repo-url: https://github.com/fnaufel/2024-DWARFF-Romulo
  repo-branch: master
  repo-actions: [edit, source, issue]
  downloads: [pdf]
  date-format: "DD/MM/YYYY HH:mm"
  sharing: 
    - twitter
    - facebook
    - linkedin
  chapters:
    - index.qmd
    - temporadas-2014-2023.qmd
    - temporadas-2014-2023-logistic.qmd
    - gerar-listas-e-rankings.qmd
    - usando-posicoes.qmd
    - references.qmd

bibliography: bibliography.bib

csl: universidade-do-porto-faculdade-de-engenharia-chicago-pt-crono.csl

comments:
  hypothesis: true

execute: 
  echo: true
  eval: true
  warning: true
  error: true
  include: true

format:
  html:
    toc-depth: 3
    number-depth: 2
    theme: 
      - journal
      - _custom.scss
    df-print: paged
    code-link: true
    code-copy: true
    code-tools: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/fnaufel\.github\.io/2024\-DWARFF\-Romulo
  pdf:
    documentclass: scrreprt
    toc-depth: 3
    number-depth: 2
    fig-pos: htb
    keep-tex: true
    df-print: tibble
    filters: 
      - filters/dollar.lua
      - filters/hl.lua
    include-in-header: 
      - _preamble.tex
    include-before-body:  
      - _before-body.tex

